<? if (!defined ("BAYOU_CORE")) error_log("Call from no bayou core") and die(); ?>
    <div id="header" class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container-fluid">
				<a class="brand" href="#">
				<!--<img src="assets/img/logo.png" alt="Conquer"/>-->
				</a>
				<a class="btn btn-navbar collapsed" id="main_menu_trigger" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="arrow"></span>
				</a>          			
				<div class="top-nav">				
					<ul class="nav pull-right" id="top_menu">
						<li class="divider-vertical hidden-phone hidden-tablet"></li>
						<li class="divider-vertical hidden-phone hidden-tablet"></li>
					</ul>	
				</div>
			</div>
		</div>
	</div>
    