<? if (!defined ("BAYOU_CORE")) error_log("Call from no bayou core") and die(); ?>
<!DOCTYPE html>
<!--[if IE 8]> <html lang="<? echo $this->codeLan ?>" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="<? echo $this->codeLan ?>" class="ie9"> <![endif]-->
<!--[if IE 10]> <html lang="<? echo $this->codeLan ?>" class="ie10"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
