<? if (!defined ("BAYOU_CORE")) error_log("Call from no bayou core") and die(); ?>
<? $this->block('meta') ?>

<head>
	<meta charset="<? echo $this->codeSite ?>" />
	<title><? echo Bayou::registry('site_name') ?></title>
	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
	
	<link rel="canonical" href="<? echo Bayou::getCanonical() ?>" />
	
	<link href="<? echo $this->getViewerSkinUrl(); ?>assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
	<link href="<? echo $this->getViewerSkinUrl(); ?>assets/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" />
	<link href="<? echo $this->getViewerSkinUrl(); ?>aassets/font-awesome/css/font-awesome.css" rel="stylesheet" />
	<link href="<? echo $this->getViewerSkinUrl(); ?>assets/css/style.css" rel="stylesheet" />
	<link href="<? echo $this->getViewerSkinUrl(); ?>assets/css/style_responsive.css" rel="stylesheet" />
	<link href="<? echo $this->getViewerSkinUrl(); ?>assets/css/style_default.css" rel="stylesheet" id="style_color" />
</head>

<? $this->block('body_open') ?>

	<? $this->block('header') ?>
	
	<div id="container" class="row-fluid">
		
		<? $this->block('side_bar') ?>
		
		<div id="body">
			
			<div class="container-fluid">
			
				<div class="row-fluid">
					<div class="span12">
						<h3 class="page-title"><? Helper::___('Gestión de Hoteles') ?></h3>
					</div>
				</div>
				
				<div id="page">
					<div class="row-fluid">
						<div class="span12">
							<div class="widget">
								<div class="widget-body form">
									<form action="" class="form-horizontal" method="get">
										<button class="btn btn-warning" type="submit" formaction="#">
											<i class="icon-plus icon-white"></i><? Helper::___('Crear Hotel') ?>
										</button>
									</form>
								</div>
							</div>
							
							<div id="hoteles" class="widget">
								<div class="widget-title">
									<h4><i class="icon-reorder"></i><? Helper::___('Hoteles') ?></h4>
									<span class="tools"></span>							
								</div>
								<div class="widget-body">
									<table class="table table-striped table-bordered" id="hotelesTable">
										<thead>
											<tr>
												<th><? Helper::___('Nombre') ?></th>
												<th>Acciones</th>
											</tr>
										</thead>
										<tbody>
											<? if (!($this->hotelesActivos->is_empty())) : ?>
											<? do { ?>
											<tr>
												<td><? echo $this->hotelesActivos->current()->nombre ?></td>
												<td>
													<a href="#" class="icon huge"><? Helper::___('Editar') ?></a>
												</td>
											</tr>
											<? } while($this->hotelesActivos->next()) ?>
											<? endif; ?>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
			
		</div>
		
	</div>

	<div id="footer">
		<div class="span pull-right">
			<span class="go-top"><i class="icon-arrow-up"></i></span>
		</div>
	</div>
	
	<script src="<? echo $this->getViewerSkinUrl(); ?>assets/js/jquery-1.8.2.min.js"></script>	
	<script src="<? echo $this->getViewerSkinUrl(); ?>assets/bootstrap/js/bootstrap.min.js"></script>
	<script src="<? echo $this->getViewerSkinUrl(); ?>assets/js/jquery.blockui.js"></script>
	<script src="<? echo $this->getViewerSkinUrl(); ?>assets/uniform/jquery.uniform.min.js"></script>
	
</body>
</html>